package JavaConcepts;

// Concept of constructor - Default Constructor

// -- Constructor is a block of code. Whenever an object is created.
// ie, whenever you create an object for the class automatically a block of code will get executed.
// That means constructor is invoked whenever you create an object.

// so where is constructor and where do you define it?
// So constructor should written it just like a method. 
// But the only difference between the method and constructor is constructor will not return any values.
// -- Constructor will not return any values.
// -- Name of constructor should be always the class name .

public class constructDemo {

	// Right now if you want to write a constuctor for this class
	// Default Constructor
	public constructDemo() { // This is a constructor; constructor is not returning any value here,

		// Constructor only return through object

// Here what ever we write in this constructor will be executed, whoever creates object to this constructDemo class name
// If you create an object for this constructDemo class name. Automatically set of lines present in this block will be executed (block means inside constructor)
// Thats the main aim of constructor.
		System.out.println("I am in the constructor");
		System.out.println("I am in the constructor lecture 1");

	}

	public constructDemo(int a, int b) { // This is parametrized constructor with 2 parameters
		System.out.println("I am in the First Parametrized constructor");
		int c = a + b;
		System.out.println(c);

	}

	public constructDemo(String str) {
		System.out.println("I am in the Second Parametrized constructor");
		System.out.println(str);
	}

	public static void getdata() { // This is a method; This method is expecting something return here

		System.out.println("I am the method");
	}

	public static void main(String[] args) {

		constructDemo cd = new constructDemo(); // Where cd is object; new is memory allocation operator
		constructDemo cd1 = new constructDemo(4, 5); // Parameterized constructor passing 2 parameters
		constructDemo cd2 = new constructDemo("Hello");

// Whenever above line or object  is executed. Automatically will check whether it is there in construtor is explicitly defined?
// If it is defined it will execute that particular block
// Whenever you create an object. constructor is called. 

	}

}

// Note 1:
// I didn't call any method, By just running constructDemo method  
// constructDemo cd = new constructDemo(); this objected is created
// So whenever an object is created constructor block is called

// Note2:
// If you don't define any constrictor. Compiler will call implicit constructor if you have not defined constructor block

// Note 3:
// When ever you create an object if you don't pass parameters automatically it will pick the default constructor.
// When you create object for the same class this time you have to passs parameters for parameterized constructors

// Note 4:
// You can create multiple objects for same class.
// If you define any constructor java compiler wil not look for an implicit constructor
// Implicit constructors are automatically generated by the compiler or the language
// while explicit constructors are defined by the programmer.
