package JavaConcepts;

//Concept of constructor - Parameterized Constructor

public class constructDemo1 {

	public constructDemo1(int a, int b) { // This is parametrized constructor
		int c = a * b;
		System.out.println("I am in the 1st Parametrized constructor: " + c);

	}

	public constructDemo1(String str) { // Singel parameterized constructor
		System.out.println("I am in the 2nd parameterized constructor: " + str);
	}

	public constructDemo1() { // If user create any object - Then only this constructor will be executed.
		System.out.println("I am in the 3rd parameterized constructor");
	}

	public static void main(String[] args) {
		constructDemo1 pc = new constructDemo1(10, 20); // Two arguments are passing
		constructDemo1 pc1 = new constructDemo1("Jenson Constructor"); // Single arguments are passing

//If user create object for constructDemo1() constructor then only this will be executed - Refer below 
		// constructDemo1 dc = new constructDemo1();
	}

}

//You can create multiple objects for same class.
//If you define any constructor java compiler wil not look for an implicit constructor
//Implicit constructors are automatically generated by the compiler or the language
//while explicit constructors are defined by the programmer.
